package com.nova.mp3;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.*;import android.media.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import java.util.*;

public class MainActivity extends Activity{
 static final int REQ=9; ArrayList<Track> songs=new ArrayList<>(); MediaPlayer mp; int page=0,pos=0,current=-1; boolean repeat,shuffle; SharedPreferences sp; Screen ui;
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("p",0);repeat=sp.getBoolean("repeat",false);shuffle=sp.getBoolean("shuffle",false);ui=new Screen(this);setContentView(ui);if(ok())scan();}
 boolean ok(){return checkSelfPermission(Build.VERSION.SDK_INT>=33?Manifest.permission.READ_MEDIA_AUDIO:Manifest.permission.READ_EXTERNAL_STORAGE)==PackageManager.PERMISSION_GRANTED;}
 void perm(){requestPermissions(new String[]{Build.VERSION.SDK_INT>=33?Manifest.permission.READ_MEDIA_AUDIO:Manifest.permission.READ_EXTERNAL_STORAGE},REQ);}
 public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&ok())scan();ui.invalidate();}
 void scan(){songs.clear();Uri u=MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;String[]q={MediaStore.Audio.Media._ID,MediaStore.Audio.Media.TITLE,MediaStore.Audio.Media.ARTIST,MediaStore.Audio.Media.DURATION};Cursor c=null;try{c=getContentResolver().query(u,q,MediaStore.Audio.Media.IS_MUSIC+"!=0",null,MediaStore.Audio.Media.TITLE+" ASC");while(c!=null&&c.moveToNext())songs.add(new Track(c.getLong(0),c.getString(1),c.getString(2),"מוזיקה",c.getLong(3),ContentUris.withAppendedId(u,c.getLong(0))));}catch(Exception e){}finally{if(c!=null)c.close();}ui.invalidate();}
 void play(int i){if(songs.isEmpty())return;current=Math.max(0,Math.min(i,songs.size()-1));release();try{mp=new MediaPlayer();mp.setDataSource(this,songs.get(current).uri);mp.setOnPreparedListener(x->{x.start();ui.invalidate();});mp.setOnCompletionListener(x->next());mp.prepareAsync();}catch(Exception e){release();}}
 void release(){if(mp!=null){try{mp.release();}catch(Exception e){}mp=null;}}
 void next(){if(songs.isEmpty())return;if(repeat){play(current);return;}play(shuffle?new Random().nextInt(songs.size()):(current+1)%songs.size());}
 void prev(){if(songs.isEmpty())return;play(current<=0?songs.size()-1:current-1);}
 void open(){if(page==0){page=pos+1;pos=0;}else if(page==1){if(!songs.isEmpty()){play(pos);page=3;}}else if(page==3){if(mp==null)play(0);else if(mp.isPlaying())mp.pause();else mp.start();}else if(page==4){if(pos==0)repeat=!repeat;else if(pos==1)shuffle=!shuffle;sp.edit().putBoolean("repeat",repeat).putBoolean("shuffle",shuffle).apply();}ui.invalidate();}
 void back(){if(page==0)finish();else{page=0;pos=0;ui.invalidate();}}
 void move(int d){int n=page==0?4:page==1?songs.size():page==4?2:1;if(n>0)pos=(pos+d+n)%n;ui.invalidate();}
 public void ctl(int c){if(!ok()){if(c==4)perm();return;}if(c==0)move(-1);if(c==1)move(1);if(c==2){if(page==3)prev();else back();}if(c==3){if(page==3)next();else open();}if(c==4)open();if(c==5)back();if(c==6){if(page==4)move(1);}}
 class Screen extends View{
  Paint p=new Paint(1);long down;Screen(Context c){super(c);}
  float d(float x){return x*getResources().getDisplayMetrics().density;}
  void t(Canvas c,String s,float x,float y,float z,int col,Paint.Align a){p.setColor(col);p.setTextSize(d(z));p.setTextAlign(a);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
  void box(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,t,r,b,d(rad),d(rad),p);}
  protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();c.drawColor(0xff07090c);box(c,d(14),d(12),w-d(14),h-d(12),0xff222831,28);t(c,"NOVA",w/2,d(43),16,0xffe0e8ef,Paint.Align.CENTER);t(c,"MP3 PLAYER",w/2,d(61),8,0xff82909b,Paint.Align.CENTER);float l=d(30),r=w-d(30),top=d(75),bot=Math.min(d(345),h*.5f);box(c,l,top,r,bot,0xff14232c,12);
   if(!ok()){t(c,"גישה למוזיקה נדרשת",w/2,top+d(70),16,Color.WHITE,Paint.Align.CENTER);t(c,"לחץ OK לאישור",w/2,top+d(100),11,0xffa9bdc9,Paint.Align.CENTER);}else{t(c,new String[]{"תפריט ראשי","מוזיקה","סייר קבצים","מנגן עכשיו","הגדרות"}[page],w/2,top+d(30),13,0xffc4d6e1,Paint.Align.CENTER);if(page==0)home(c,l,r,top);if(page==1)list(c,l,r,top);if(page==3)now(c,w,top);if(page==4)settings(c,l,r,top);}controls(c,w,h);}
  void home(Canvas c,float l,float r,float y){String[]a={"מוזיקה","סייר קבצים","מנגן עכשיו","הגדרות"};for(int i=0;i<4;i++){float z=y+d(64+i*35);if(pos==i)box(c,l+d(12),z-d(20),r-d(12),z+d(10),0xff2d617d,7);t(c,a[i],r-d(25),z,12,pos==i?Color.WHITE:0xffaab9c4,Paint.Align.RIGHT);}}
  void list(Canvas c,float l,float r,float y){if(songs.isEmpty()){t(c,"לא נמצאו קבצי מוזיקה",getWidth()/2,y+d(90),14,Color.WHITE,Paint.Align.CENTER);return;}int f=Math.max(0,Math.min(pos-3,Math.max(0,songs.size()-6)));for(int i=f;i<Math.min(songs.size(),f+6);i++){Track s=songs.get(i);float z=y+d(62+(i-f)*34);if(i==pos)box(c,l+d(10),z-d(19),r-d(10),z+d(10),0xff2d617d,7);String n=s.title.length()>25?s.title.substring(0,24)+"…":s.title;t(c,n,r-d(22),z,10,i==pos?Color.WHITE:0xffb6c5ce,Paint.Align.RIGHT);t(c,s.time(),l+d(20),z,9,0xff8498a5,Paint.Align.LEFT);}}
  void now(Canvas c,float w,float y){if(current<0){t(c,"אין רצועה פעילה",w/2,y+d(90),14,Color.WHITE,Paint.Align.CENTER);return;}Track s=songs.get(current);t(c,s.title,w/2,y+d(72),15,0xfff0f6fa,Paint.Align.CENTER);t(c,s.artist,w/2,y+d(97),10,0xff9db2bf,Paint.Align.CENTER);t(c,mp!=null&&mp.isPlaying()?"▶ מנגן":"Ⅱ מושהה",w/2,y+d(145),12,0xffdcecf5,Paint.Align.CENTER);postInvalidateDelayed(700);}
  void settings(Canvas c,float l,float r,float y){String[]a={"חזרה: "+(repeat?"כן":"לא"),"ערבוב: "+(shuffle?"כן":"לא")};for(int i=0;i<2;i++){float z=y+d(70+i*42);if(pos==i)box(c,l+d(12),z-d(20),r-d(12),z+d(10),0xff2d617d,7);t(c,a[i],r-d(22),z,11,pos==i?Color.WHITE:0xffb6c5ce,Paint.Align.RIGHT);}}
  void controls(Canvas c,float w,float h){float y=h-d(120),x=w/2;btn(c,x,y-d(55),"▲",45);btn(c,x,y+d(55),"▼",45);btn(c,x-d(58),y,"‹",45);btn(c,x+d(58),y,"›",45);btn(c,x,y,"OK",52);box(c,d(20),y-d(19),d(92),y+d(19),0xff2b3239,12);t(c,"חזור",d(56),y+d(4),9,0xffd8e1e7,Paint.Align.CENTER);box(c,w-d(92),y-d(19),w-d(20),y+d(19),0xff2b3239,12);t(c,"אפשר",w-d(56),y+d(4),9,0xffd8e1e7,Paint.Align.CENTER);}
  void btn(Canvas c,float x,float y,String s,float z){p.setColor(0xff303841);p.setStyle(Paint.Style.FILL);c.drawCircle(x,y,d(z),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setColor(0xff626d78);c.drawCircle(x,y,d(z),p);p.setStyle(Paint.Style.FILL);t(c,s,x,y+d(6),s.equals("OK")?11:18,0xffe7eef3,Paint.Align.CENTER);}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight(),cy=h-d(120);if(Math.hypot(x-w/2,y-(cy-d(55)))<d(52))ctl(0);else if(Math.hypot(x-w/2,y-(cy+d(55)))<d(52))ctl(1);else if(Math.hypot(x-(w/2-d(58)),y-cy)<d(52))ctl(2);else if(Math.hypot(x-(w/2+d(58)),y-cy)<d(52))ctl(3);else if(Math.hypot(x-w/2,y-cy)<d(57))ctl(4);else if(Math.abs(x-d(56))<d(38)&&Math.abs(y-cy)<d(24))ctl(5);else if(Math.abs(x-(w-d(56)))<d(38)&&Math.abs(y-cy)<d(24))ctl(6);return true;}
 }
}